import React from 'react';

export const metadata = {
    title: "Stats | KeenKeeper",
    description: "Generated by create next app",
};

const StatsPage = () => {
    return (
        <div>

            <p>this is state page</p>

        </div>
    );
};

export default StatsPage;