import PiChart from "@/Components/PiChart/PiChart";


export const metadata = {
    title: "Stats | KeenKeeper",
    description: "Generated by create next app",
};

const StatsPage = () => {
    
    return (
        <div className="m-15">
            <h2 className="text-5xl font-bold mb-8">Friendship Analytics</h2>

            <PiChart></PiChart>

        </div>
    );
};

export default StatsPage;