import StoredFriends from '@/Components/StoredFriends/StoredFriends';
import React from 'react';

export const metadata = {
    title: "Timeline | KeenKeeper",
    description: "Generated by create next app",
};

const TimelinePage = () => {
    return (
        <div className="py-5 px-5 md:py-10 md:px-20">

            <h2 className='text-5xl font-bold my-8'>Timeline</h2>
            <StoredFriends></StoredFriends>

        </div>
    );
};

export default TimelinePage;