import Image from 'next/image';
import { HiBellSnooze } from 'react-icons/hi2';
import { FaBoxArchive } from 'react-icons/fa6';
import { MdDeleteForever } from 'react-icons/md';
import FriendDetailsBtn from '@/Components/FriendDetailsBtn/FriendDetailsBtn';


export const metadata = {
    title: "Friend Details",
    description: "Generated by create next app",
};

const FriendsDetailsPage = async ({ params }) => {
    const { friendId } = await params;
    // console.log(friendId)
    const res = await fetch("https://a-7keen-keeper.vercel.app/friends.json");
    const friends = await res.json();
    // console.log(friends)
    const detailsFriend = friends.find(friend => friend.id === Number(friendId));
    // console.log(detailsFriend)
    const { name, picture, email, days_since_contact, status, tags, bio, goal, next_due_date } = detailsFriend;

    return (
        <div className='grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5 grid-rows-7 py-2 px-2 lg:py-10 lg:px-20 gap-5'>
            <div className='flex flex-col justify-center items-center p-5 bg-white  rounded-2xl space-y-4 row-span-4 col-span-2'>
                <div>
                    <Image
                        src={picture}
                        alt={name}
                        width={100}
                        height={100}
                        className='rounded-full border border-gray-300'
                    ></Image>
                </div>
                <h2 className='text-2xl font-bold'>{name}</h2>
                <p className={`border bg-amber-200 ${status == "on-track" && "bg-green-800 text-white"} ${status == "overdue" && "bg-red-600 text-white"} ${status == "almost due" && "bg-yellow-500 text-white"} rounded-2xl py-1 px-2`}>{status}</p>
                <div className='flex gap-2'>
                    {
                        tags.map((tag, i) => <span className='bg-green-200 px-2 rounded-2xl flex justify-center items-center py-1' key={i}>{tag}</span>)
                    }
                </div>
                <p className='text-gray-500'>Email: {email}</p>
            </div>

            <div className='bg-white text-center rounded-2xl shadow p-6 space-y-3 col-span-1 row-span-2 flex flex-col justify-center items-center'>
                <p className=' font-bold text-xl'>{days_since_contact}</p>
                <p className='text-gray-500'>Days Since Contact</p>
            </div>
            <div className='bg-white text-center rounded-2xl shadow p-6 space-y-3 col-span-1 row-span-2 flex flex-col justify-center items-center'>
                <p className=' font-bold text-xl'>{goal}</p>
                <p className='text-gray-500'>Goals (30 days)</p>
            </div>
            <div className='bg-white text-center rounded-2xl shadow p-6 space-y-3 col-span-1 row-span-2 flex flex-col justify-center items-center'>
                <p className='text-3xl text-green-800 font-semibold'>{next_due_date}</p>
                <p className='text-gray-500'>Next Due</p>
            </div>
            <div className='bg-white rounded-2xl shadow p-6 space-y-3 col-span-3 row-span-2'>
                <div className='flex justify-between items-center'>
                    <h2 className='text-2xl font-bold'>Relationships Goals</h2>
                    <button className='btn'>Edit</button>
                </div>
                <p><span className='text-gray-500'>Connected every</span> <span className='font-bold'>30 days</span></p>
            </div>

            <div className='row-span-1 col-span-2 bg-white rounded-xl flex justify-center items-center'>
                <p className='flex gap-1 justify-center items-center text-xl'>
                    <span><HiBellSnooze /></span>
                    <span>Snooze 2 Weeks</span>
                </p>
            </div>

            <div className='bg-white rounded-2xl shadow p-6 space-y-5 col-span-3 row-span-3'>
                <h2 className='text-xl'>Quick Check-In</h2>
                <FriendDetailsBtn detailsFriend={detailsFriend} ></FriendDetailsBtn>
            </div>

            <div className='row-span-1 col-span-2 bg-white rounded-xl flex justify-center items-center'>
                <p className='flex gap-1 justify-center items-center text-xl'>
                    <span><FaBoxArchive /></span>
                    <span>Archive</span>
                </p>
            </div>
            
            <div className='row-span-1 col-span-2 bg-white rounded-xl flex justify-center items-center'>
                <p className='flex gap-1 justify-center items-center text-xl'>
                    <span><MdDeleteForever /></span>
                    <span>Delete</span>
                </p>
            </div>
        </div>
    );
};

export default FriendsDetailsPage;